---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/trueprofile.joycorporatesolutions.com/
    - /bin/cp -Rf dist/* $DEPLOYPATH 2>/dev/null || true
    - /bin/cp -Rf dist/* /home/$USER/public_html/trueprofile/ 2>/dev/null || true
    - /bin/cp -Rf dist/* /home/$USER/public_html/trueprofile.joycorporatesolutions.com/ 2>/dev/null || true
    - /bin/cp -Rf dist/* /home/$USER/public_html/ 2>/dev/null || true
    - mkdir -p tmp 2>/dev/null || true
    - touch tmp/restart.txt 2>/dev/null || true
    - touch passenger_wsgi.py 2>/dev/null || true
